name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=resize_image_app_icon.ico --name="Image Resizer" image_resizer.py

    - name: Package files
      run: |
        Compress-Archive -Path dist\* -DestinationPath ImageResizer_Setup.zip -Force

    - name: Upload executable
      uses: actions/upload-artifact@v4  # Updated version
      with:
        name: Image-Resizer-Executable
        path: dist/*
