name: Build AppImage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: 3.10

    - name: Install FUSE
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create AppDir structure
      run: |
        mkdir -p AppDir/usr/{bin,share/{applications,icons/hicolor/128x128/apps}}
        
    - name: Check Required Files
      run: |
        if [ ! -f "resize_image_app_icon.ico" ]; then
          echo "Error: resize_image_app_icon.ico does not exist."
          exit 1
        fi
        if [ ! -f "image_resizer.py" ]; then
          echo "Error: image_resizer.py does not exist."
          exit 1
        fi
        
    - name: Install ImageMagick and Convert Icon
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        convert resize_image_app_icon.ico AppDir/usr/share/icons/hicolor/128x128/apps/image-resizer.png || { echo "Icon conversion failed"; exit 1; }

    - name: Create desktop file
      run: |
        cat > AppDir/usr/share/applications/image-resizer.desktop << 'EOF'
        [Desktop Entry]
        Name=Image Resizer
        Comment=Batch resize images with ease
        Exec=image-resizer
        Icon=image-resizer
        Terminal=false
        Type=Application
        Categories=Graphics;Utility;
        EOF

    - name: PyInstaller Build
      run: |
        pyinstaller --onefile --name image-resizer image_resizer.py
        cp dist/image-resizer AppDir/usr/bin/
        chmod +x AppDir/usr/bin/image-resizer

    - name: Create AppRun file
      run: |
        cat > AppDir/AppRun << 'EOF'
        #!/bin/bash
        SELF=$(readlink -f "$0")
        HERE=${SELF%/*}
        export PATH="${HERE}/usr/bin:${PATH}"
        export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
        "${HERE}/usr/bin/image-resizer" "$@"
        EOF
        chmod +x AppDir/AppRun

    - name: Create Symlinks
      run: |
        ln -s usr/share/applications/image-resizer.desktop AppDir/image-resizer.desktop
        ln -s usr/share/icons/hicolor/128x128/apps/image-resizer.png AppDir/image-resizer.png

    - name: Download AppImageTool
      run: |
        wget -O appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Build AppImage
      run: |
        ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir
        mv Image_Resizer*.AppImage Image_Resizer-x86_64.AppImage  # Rename for consistency

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: image-resizer-appimage
        path: Image_Resizer-x86_64.AppImage  # Corrected artifact path
