name: Build AppImage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install FUSE
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create AppDir structure
      run: |
        mkdir -p AppDir/usr/{bin,share/{applications,icons/hicolor/128x128/apps}}

    - name: Copy Icon to AppDir
      run: |
        cp image-resizer-icon.png AppDir/usr/share/icons/hicolor/128x128/apps/image-resizer-icon.png

    - name: Create desktop file
      run: |
        cat > AppDir/usr/share/applications/image-resizer.desktop << 'EOF'
        [Desktop Entry]
        Name=Image Resizer
        Comment=Batch resize images with ease
        Exec=image-resizer
        Icon=image-resizer-icon
        Terminal=false
        Type=Application
        Categories=Utility;
        EOF

    - name: PyInstaller build
      run: |
        pyinstaller --onefile --name image-resizer ./image_resizer.py
        cp dist/image-resizer AppDir/usr/bin/
        chmod +x AppDir/usr/bin/image-resizer

        # Create AppRun file
        cat > AppDir/AppRun << 'EOF'
        #!/bin/bash
        SELF=$(readlink -f "$0")
        HERE=${SELF%/*}
        export PATH="${HERE}/usr/bin:${PATH}"
        export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
        "${HERE}/usr/bin/image-resizer" "$@"
        EOF
        chmod +x AppDir/AppRun

        # Create symlinks
        ln -sf usr/share/applications/image-resizer.desktop AppDir/image-resizer.desktop
        ln -sf usr/share/icons/hicolor/128x128/apps/image-resizer-icon.png AppDir/image-resizer-icon.png

    - name: Download AppImageTool
      run: |
        wget -O appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Build AppImage
      run: |
        ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: image-resizer-appimage
        path: Image_Resizer*.AppImage
